### PR TITLE
Redesign icons / dark and light support and README updates

### PR DESCRIPTION
**Pull request by ardacebi**
This pull request includes the separation of the current single directory of MerOS' icons (e.g. folders) to two other directories called dark and light.

The new icons will have the Mercode color on **the icon itself** and not the background. The background on the other hand will feature `#2e2e2e` for dark mode, and `#e9e9e9` for light mode.

### Planned phases
6 phases for dark, 6 phases for light.

### Issues
Below are the encountered issues.

#### Dark
- [x] **folder-blue-visiting.svg** - Lines too orange (possible issue)
- [x] **folder-blue-java.svg** - 1. Not seems to be working on my computer, image getting saved outside svg file 2. Image cannot be edited, color should be changed to Mercode color
- [x] **folder-blue-mega.svg** - Decision on MEGA icon, should it be using the red color or the Mercode color?

#### Light
- [x] **folder-blue-desktop.svg** - What's the secondary light color?
- [x] **folder-blue-java.svg** - Because of being an image, cannot be converted to Mercode color

### Important
We should test the icons before merging to master. While saving the .svg files, there's a change being made by Illustrator causing the files to be larger than they should be. This probably shouldn't affect the functionality of them but it is useful to test even if it doesn't.

### CODE REVIEW

**Comment by mkg20001** [comment]
I think it would be better if we'd take the current papirus icon theme's history as base so we can rebase stuff before doing such changes

Also since the diff is huge, can you give me a tl;dr?

@Yutyo This should've been done with all repos, especially papirus icon theme, since now there's no sane way to get the new icons that get added to papirus icon theme by the papirus team

**Comment by mkg20001** [comment]
They have a dark theme https://github.com/PapirusDevelopmentTeam/papirus-icon-theme so clearly we should just rebase that

**Comment by tansiret** [comment]
> They have a dark theme https://github.com/PapirusDevelopmentTeam/papirus-icon-theme so clearly we should just rebase that

Nope. There are other changes that I have made apart from icon colors, such as new apps and better design than those made by Papirus team + we are making designs according to our own color guidelines and styles. Also, even Manjaro team that has only changed the colors of folders just maintain a separate [Papirus icon theme](https://github.com/Ste74/papirus-maia-icon-theme), not even a fork.

**Comment by ardacebi** [comment]
> Also since the diff is huge

I've temporarily duplicated the directory in which the current icons are located which is located in root. I've created two directories called dark and light to change their colors to the values we've discussed with @Yutyo.  

The color and icon situation will be clear when I finish with the design guidelines. I plan to add a section specifically for MerOS for things like the folder icons, their colors etc.

**Pull request merged**
